### ISSUE TITLE
Error in private$request(url, data) :Bad Request (HTTP 400).

### ISSUE THREAD

**Issue by ilsafaust** [ebeneditos/telegram.ext#18]
Please choose one of the following and fill the appropriate field: 

## Bug Report (or a question)

I'm trying to send message from Bot for a chat_id's from the array (df$telegram_id). Sometimes I get the following error:

 private$request(url, data) :Bad Request (HTTP 400).

I suppose that this is because of some private settings of some chats. If there are only chat_id's in the array that can receive messages from Bot everything is ok.

Could you please help how I can skip the chat_id's with this error?

The function for sending message is below:

send_messages <- function(df) {
  
  for (k in 1:nrow(df)) {

    updater$bot$sendMessage(parse_mode = "Markdown", chat_id = df$telegram_id[k], text = df$message[k])

	}
  }

**Comment by krose** [comment]
Just to chip in. @ilsafaust Perhaps you run into the character limit at something near 4K characters, so some messages might need to be split up.
